language: php

## PHP versions we test against
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update -q
  - if [ -z "$dependencies" ]; then composer install; fi;

## Run the actual test
script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml

after_script: sh -c " if [ -f ./build/logs/clover.xml ]; then php vendor/bin/coveralls; fi"
